# Description: Scalar wind plot and Skew-t configuration
# Author: Leah Herrfurth
# Edited by: Lina Br√ºckner (Adding scalar_wind and skewT)




plot_type: scalar_wind    # Generate a scalar field with wind vectors

scalar_wind:
  parameter: z            # Geopotential height
  level: 500              # Pressure level in hPa
  u: u                     # Zonal wind component
  v: v                     # Meridional wind component

skewT:
  lat: 48.21              # Latitude for Skew-T diagram
  lon: 16.37              # Longitude for Skew-T diagram


time: "2025-10-02T00:00"  # Time of the data to visualize
directory: "./"         # Directory to save outputs
no_browser: true    # Do not open the browser automatically
download_data: false  # Do not download data 


vert_cross:
  parameter: z
  lat0: 40
  lon0: 0
  lat1: 60
  lon1: 20
  npoints: 200

