plot_type: scalar_wind   # default plot type

scalar_wind:
  parameter: z
  u: u
  v: v
  level: 500
  time: 2025-10-01T00:00

skewT:
  lat: 48.21
  lon: 16.37
  time: 2025-10-01T00:00

common:
  datafile: "../data/era5_example_1.nc"
  no_browser: true
  directory: "./"
