plot_type: scalar_wind

scalar_wind:
  parameter: z
  level: 500
  u: u
  v: v

skewT:
  lat: 48.21
  lon: 16.37

common:
  time: "2025-12-01T00:00"
  directory: "./"
  no_browser: true
  download_data: false
